### ISSUE TITLE
DJL on Inferentia with a huggingface model

### ISSUE THREAD

**Issue by aamirbutt** [deepjavalibrary/djl-demo#200]
Hi,

So I have been able to successfully run a BERT model in Inferentia with DJL using djl-serving. 

What I am trying to do now is to write my own java app with DJL and try and run the neuron-scripted model on an Inferentia instance (inf1). My code to load model is simply the following:

```
    public boolean initialize() {
        BertTranslator translator = new BertTranslator(vocabPath);
        Criteria<QAInput, String> criteria = Criteria.builder()
                .setTypes(QAInput.class, String.class)
                .optModelPath(modelPath)
                .optModelName(modelName)
                .optTranslator(translator)
                .optEngine("PyTorch") // Use PyTorch engine
                .optProgress(new ProgressBar()).build();

        try {
            var model = criteria.loadModel();
            this.predictor = model.newPredictor(translator);
            return true;
        } catch (Exception ex) {
            System.out.println("Error while loading model: ");
            ex.printStackTrace();
            return false;
        }
    }
```
The translator is my own and is very simple. I can paste that code here too if needed.

Anyway, the Exception that I get is the following:

```
Error while loading model:
ai.djl.engine.EngineException: Failed to load PyTorch native library
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:77)
        at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
        at ai.djl.engine.Engine.getEngine(Engine.java:168)
        at ai.djl.Model.newInstance(Model.java:98)
        at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:187)
        at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:149)
        at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:166)
        at ai.zir.djl.BertPredictor.initialize(BertPredictor.java:36)
        at ai.zir.djl.DjlTest.main(DjlTest.java:14)
Caused by: java.lang.UnsatisfiedLinkError: /home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/lib/libtorchneuron.so: /home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/lib/libtorchneuron.so: undefined symbol: _ZN6caffe28TypeMeta13_typeMetaDataISsEEtv
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2440)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2497)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:744)
        at java.base/java.lang.System.load(System.java:1870)
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:72)
        ... 8 more
```

I have set all the required environment variables as well like following:

```
export PYTORCH_EXTRA_LIBRARY_PATH=$(python -m site | grep $VIRTUAL_ENV | awk -F"'" '{print $2}')/torch_neuron/lib/libtorchneuron.so
export PYTORCH_PRECXX11=true
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(python -m site | grep $VIRTUAL_ENV | awk -F"'" '{print $2}')/torch/lib/:$(python -m site | grep $VIRTUAL_ENV | awk -F"'" '{print $2}')/torch_neuron/lib/
```

it looks like somehow `PRECX11` pytorch version is not being used. What can I do to have this working?

**Comment by frankfliu** [comment]
@aamirbutt 

Can you enable debug logging level and see where the libtorch.so file is DJL loaded from.
Which version of DJL are you using?

**Comment by aamirbutt** [comment]
@frankfliu Thanks for your response. 
Here is the logging with Debug enabled. I am using djl 0.13.0

```
0 [main] DEBUG ai.djl.repository.zoo.DefaultModelZoo  - Scanning models in repo: class ai.djl.repository.SimpleRepository, file:/home/ubuntu/code/bert_test/data/question_answering.pt
7 [main] DEBUG ai.djl.repository.zoo.ModelZoo  - Loading model with Criteria:
        Application: UNDEFINED
        Input: class ai.djl.modality.nlp.qa.QAInput
        Output: class java.lang.String
        Engine: PyTorch
        ModelZoo: ai.djl.localmodelzoo

8 [main] DEBUG ai.djl.repository.zoo.ModelZoo  - Searching model in specified model zoo: ai.djl.localmodelzoo
11 [main] DEBUG ai.djl.engine.Engine  - Found EngineProvider: PyTorch
12 [main] DEBUG ai.djl.engine.Engine  - Found default engine: PyTorch
12 [main] WARN ai.djl.repository.SimpleRepository  - Simple repository pointing to a non-archive file.
15 [main] DEBUG ai.djl.repository.zoo.ModelZoo  - Checking ModelLoader: ai.djl.localmodelzoo:question_answering.pt UNDEFINED [
        ai.djl.localmodelzoo/question_answering.pt/question_answering.pt {}
]
16 [main] DEBUG ai.djl.repository.MRL  - Preparing artifact: file:/home/ubuntu/code/bert_test/data/question_answering.pt, ai.djl.localmodelzoo/question_answering.pt/question_answering.pt {}
16 [main] DEBUG ai.djl.repository.SimpleRepository  - Skip prepare for local repository.
Loading:     100% |████████████████████████████████████████|
142 [main] WARN ai.djl.util.cuda.CudaUtils  - Failed to detect GPU count: no CUDA-capable device is detected (38)
142 [main] WARN ai.djl.util.cuda.CudaUtils  - Failed to detect GPU count: no CUDA-capable device is detected (38)
144 [main] DEBUG ai.djl.pytorch.jni.LibUtils  - Using cache dir: /home/ubuntu/.djl.ai/pytorch
144 [main] WARN ai.djl.util.cuda.CudaUtils  - Failed to detect GPU count: no CUDA-capable device is detected (38)
145 [main] DEBUG ai.djl.pytorch.jni.LibUtils  - Loading pytorch library from: /home/ubuntu/.djl.ai/pytorch/1.9.1-cpu-linux-x86_64/0.13.0-cpu-libdjl_torch.so
248 [main] INFO ai.djl.pytorch.engine.PtEngine  - Number of inter-op threads is 2
248 [main] INFO ai.djl.pytorch.engine.PtEngine  - Number of intra-op threads is 4
251 [main] ERROR ai.zir.djl.BertPredictor  - Error while loading model: Failed to load PyTorch native library
ai.djl.engine.EngineException: Failed to load PyTorch native library
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:77)
        at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
        at ai.djl.engine.Engine.getEngine(Engine.java:168)
        at ai.djl.Model.newInstance(Model.java:98)
        at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:187)
        at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:149)
        at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:166)
        at ai.zir.djl.BertPredictor.initialize(BertPredictor.java:40)
        at ai.zir.djl.DjlTest.main(DjlTest.java:23)
Caused by: java.lang.UnsatisfiedLinkError: /home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/lib/libtorchneuron.so: /home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/lib/libtorchneuron.so: undefined symbol: _ZN6caffe28TypeMeta13_typeMetaDataISsEEtv
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2440)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2497)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:744)
        at java.base/java.lang.System.load(System.java:1870)
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:72)
        ... 8 more
        
```

**Comment by frankfliu** [comment]
@aamirbutt 

Only 0.14.0+ support `PYTORCH_PRECXX11` environment variable. And Inferentia must use precxx11 version of libtorch.

**Comment by aamirbutt** [comment]
Thanks, changing it to 0.14.0 solved the problem.

**Comment by aamirbutt** [comment]
@frankfliu Thanks for your help. I have posted another question regarding `predict` not working. Can you please take a look?
https://github.com/deepjavalibrary/djl-demo/issues/203

I am sorry for pestering you with all these, but you are the only one responding. Thanks a lot.
