### ISSUE TITLE
DJL on Inferentia causing error on Predict with Huggingface model

### ISSUE THREAD

**Issue by aamirbutt** [deepjavalibrary/djl-demo#203]
With a neuron-traced bert model in my own Java code, I was able to load model successfully with DJL 0.14.0. 

However, now when I run predict, I am getting an error. 
Following is the code which calls predict:
```
    public boolean initialize() {
        BertTranslator translator = new BertTranslator(vocabPath);
        Criteria<QAInput, String> criteria = Criteria.builder()
                .setTypes(QAInput.class, String.class)
                .optModelPath(modelPath)
                .optModelName(modelName)
                .optTranslator(translator)
                .optEngine("PyTorch") // Use PyTorch engine
                .optProgress(new ProgressBar()).build();

        try {
            var model = criteria.loadModel();
            this.predictor = model.newPredictor(translator);
            logger.info("Model loaded successfully...");
            return true;
        } catch (Exception ex) {
            logger.error("Error while loading model: " + ex.getMessage());
            ex.printStackTrace();
            return false;
        }
    }

    public String predict(String question, String paragraph) {
        if (this.predictor == null)
            return "";
        try {
            return predictor.predict(new QAInput(question, paragraph));
        } catch (TranslateException e) {
            e.printStackTrace();
            return "";
        }
    }
    
```

And here is the error that I am getting:

```
ai.djl.translate.TranslateException: ai.djl.engine.EngineException: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch_neuron/convert.py", line 20, in forward
    _5 = torch.slice(_4, 1, 0, _2)
    _6 = torch.embedding(CONSTANTS.c2, argument_1, 0)
    _7 = torch.add(_6, torch.embedding(CONSTANTS.c3, _5))
         ~~~~~~~~~ <--- HERE
    _8 = _0.model
    _9, _10 = ops.neuron.forward_v2_2([_7, argument_2], _8)

Traceback of TorchScript, original code (most recent call last):
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/resolve_function.py(68): func_from_schema
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/graph.py(328): __call__
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/graph.py(205): run_op
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/graph.py(194): __call__
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/convert.py(220): forward
/home/ubuntu/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/home/ubuntu/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(1051): _call_impl
/home/ubuntu/myenv/lib/python3.6/site-packages/torch/jit/_trace.py(959): trace_module
/home/ubuntu/myenv/lib/python3.6/site-packages/torch/jit/_trace.py(744): trace
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/convert.py(186): trace
trace.py(61): transformers_model_downloader
trace.py(78): <module>
RuntimeError: The size of tensor a (41) must match the size of tensor b (128) at non-singleton dimension 1

        at ai.djl.inference.Predictor.batchPredict(Predictor.java:186)
        at ai.djl.inference.Predictor.predict(Predictor.java:123)
        at ai.zir.djl.BertPredictor.predict(BertPredictor.java:55)
        at ai.zir.djl.DjlTest.processInputs(DjlTest.java:45)
        at ai.zir.djl.DjlTest.main(DjlTest.java:27)
Caused by: ai.djl.engine.EngineException: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch_neuron/convert.py", line 20, in forward
    _5 = torch.slice(_4, 1, 0, _2)
    _6 = torch.embedding(CONSTANTS.c2, argument_1, 0)
    _7 = torch.add(_6, torch.embedding(CONSTANTS.c3, _5))
         ~~~~~~~~~ <--- HERE
    _8 = _0.model
    _9, _10 = ops.neuron.forward_v2_2([_7, argument_2], _8)

Traceback of TorchScript, original code (most recent call last):
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/resolve_function.py(68): func_from_schema
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/graph.py(328): __call__
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/graph.py(205): run_op
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/graph.py(194): __call__
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/convert.py(220): forward
/home/ubuntu/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/home/ubuntu/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py(1051): _call_impl
/home/ubuntu/myenv/lib/python3.6/site-packages/torch/jit/_trace.py(959): trace_module
/home/ubuntu/myenv/lib/python3.6/site-packages/torch/jit/_trace.py(744): trace
/home/ubuntu/myenv/lib/python3.6/site-packages/torch_neuron/convert.py(186): trace
trace.py(61): transformers_model_downloader
trace.py(78): <module>
RuntimeError: The size of tensor a (41) must match the size of tensor b (128) at non-singleton dimension 1

        at ai.djl.pytorch.jni.PyTorchLibrary.moduleForward(Native Method)
        at ai.djl.pytorch.jni.IValueUtils.forward(IValueUtils.java:46)
        at ai.djl.pytorch.engine.PtSymbolBlock.forwardInternal(PtSymbolBlock.java:126)
        at ai.djl.nn.AbstractBlock.forward(AbstractBlock.java:126)
        at ai.djl.nn.Block.forward(Block.java:122)
        at ai.djl.inference.Predictor.predictInternal(Predictor.java:137)
        at ai.djl.inference.Predictor.batchPredict(Predictor.java:177)
        ... 4 more
     
```

**Comment by frankfliu** [comment]
@aamirbutt 

1. Are you able to run your model with Python code?
2. Does your `BertTranslator` generate the same shape as the Python code?
3. Did you pad the token to max length, Inferentia doesn't support dynamic shape, so you must use padding when you trace the model.

**Comment by aamirbutt** [comment]
It was a problem with padding. Didn't know that Inferentia doesn't support dynamic shape. Padding the data to the shape with which it was traced (128) worked. 
Thanks.
