### ISSUE TITLE
Failed to load Huggingface native library

### ISSUE THREAD

**Issue by yjh01** [deepjavalibrary/djl-demo#344]
i run the  QuestionAnswering example, but shows  "Failed to load Huggingface native library", can  you help  me slove  the problem?

maven :
```
    <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
            <version>0.22.1</version>
        </dependency>
        <dependency>
            <groupId>ai.djl.huggingface</groupId>
            <artifactId>tokenizers</artifactId>
            <version>0.22.1</version>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-engine</artifactId>
            <version>0.22.1</version>
        </dependency>
```
code :

       public static void main(String[] args) throws IOException, ModelException, TranslateException {
              String question = "When did BBC Japan start broadcasting?";
              String paragraph =
                      "BBC Japan was a general entertainment Channel. "
                              + "Which operated between December 2004 and April 2006. "
                              + "It ceased operations after its Japanese distributor folded.";
      
              Criteria<QAInput, String> criteria =
                      Criteria.builder()
                              .setTypes(QAInput.class, String.class)
                              .optModelUrls(
                                      "djl://ai.djl.huggingface.pytorch/deepset/minilm-uncased-squad2")
                              .optEngine("PyTorch")
                              .optTranslatorFactory(new QuestionAnsweringTranslatorFactory())
                              .optProgress(new ProgressBar())
                              .build();
      
              try (ZooModel<QAInput, String> model = criteria.loadModel();
                   Predictor<QAInput, String> predictor = model.newPredictor()) {
                  QAInput input = new QAInput(question, paragraph);
                  String res = predictor.predict(input);
                  System.out.println("answer: " + res);
              }
          }

       

exception:
```
         Exception in thread "main" ai.djl.engine.EngineException: Failed to load Huggingface native library.
	            at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:43)
	            at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:150)
	            at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:135)
	            at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer$Builder.build(HuggingFaceTokenizer.java:759)
	            at ai.djl.huggingface.translator.QuestionAnsweringTranslatorFactory.newInstance(QuestionAnsweringTranslatorFactory.java:65)
	            at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:162)
	            at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172)
	            at QuestionAnswering.main(QuestionAnswering.java:33)
            Caused by: java.lang.IllegalStateException: Cannot copy jni files
	            at ai.djl.huggingface.tokenizers.jni.LibUtils.copyJniLibraryFromClasspath(LibUtils.java:108)
	            at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:66)
	            at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41)
	            ... 7 more
            Caused by: java.nio.file.AccessDeniedException: D:\Users\.djl.ai\tokenizers\tmp11007201415283703111 -> D:\Users\.djl.ai\tokenizers\0.13.2-0.22.1-win-x86_64
	            at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	            at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	            at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:309)
	            at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
	            at java.base/java.nio.file.Files.move(Files.java:1422)
	            at ai.djl.util.Utils.moveQuietly(Utils.java:132)
	            at ai.djl.huggingface.tokenizers.jni.LibUtils.copyJniLibraryFromClasspath(LibUtils.java:105)
	            ... 9 more
```

**Comment by frankfliu** [comment]
@yjh01 

I have seen this issue before, but I don't really know the root cause. Something related to your windows file system. Your machine get into a really strange state.

The exception comes from this line: https://github.com/deepjavalibrary/djl/blob/master/api/src/main/java/ai/djl/util/Utils.java#L132

I tried to debug into Java code, can could not figure out what's wrong with the file system.

You can try to reboot your windows, or change your cache directory to different volume, or try another windows.

**Comment by yjh01** [comment]
i try  it success in macos , but  still can not run  in  windows.

thank  you fou your  answer.
